### ISSUE TITLE
Best practice use, and flow

### ISSUE THREAD

**Issue by airTradies** [code-and-co/react-native-image-offline#19]
Hi. Great job on this. I have read all your doco, but, 3 questions...
1) What excactly does OfflineImageStore.restore do? The code comments say to run on app startup. From the code it seems to just load all image details from AsyncStorage and then clear those that are expired. Is that correct? It doesn't do anything else?
2) What exactly does OfflineImageStore.preLoad do? The code makes it looks like it just starts downloading and storing the images that aren't in the store. Nothing else?
3) So if my assumptions above are correct, then if a remote image changes, the store won't update until the timeout is reached?

Thanks :)

EDIT: And if the images we are storing are a bit more dynamic (i.e. profile pics of other users that the current user is interacting with), then when we add a new uri in an <Offline Image> should we be running either of these functions?

**Comment by BHesseldieck** [comment]
Hey, thanks :)

You answered question 1 correctly. 

Regarding Q2: preload is for the purpose to preload images if you know the URIs upfront in order to load views faster. Images already in the store aren't load again. But you can also lazy load them on demand.

Regarding Q3: our library doesn't check if the image content is the same and just fetches it again if it times out. However, if the URI changes its a different image for our library so it will be loaded and stored.

We have built an option to fetch an image every time with out storing it as written in the documentation: 

> You can always re-fetch the image by specifying reloadImage={true} irrespective of the image already being stored offline, this way you can refresh/load the most recently updated images.

Regarding your edit: Whenever you change the URI, the image will be fetched, because it will be not in the store. You can preload it if you want to, then you just need to replace/add the URI to your prefetch URIs otherwise you can lazy load it the normal way.

Hopefully this helps.

Cheers
