### ISSUE TITLE
Not refreshing if new source is image from local storage

### ISSUE THREAD

**Issue by ywongweb** [code-and-co/react-native-image-offline#4]
Image doesn't refresh if the new source is from local storage.

**Comment by jjayasagar** [comment]
Thank you @ywongweb for creating this!

Could you bit elaborate more on usecase.  If I understand it well, First, you load an image from internet/server and then you want to load it from local storage instead of cache storage right ?

Overall, I am not sure whether we want to support local storage image URI as we can also directly use RN Image component instead OfflineImage component based on your functionality :)

Thanks!!

**Comment by jjayasagar** [comment]
Not heard on this. Closing it to manage the issues well.
